<?php

$area_terms = array(
	'niiza' => '新座市',
	'asaka' => '朝霞市',
	'wako' => '和光市',
  'oomiya' => 'さいたま市大宮区',
  'urawa' => 'さいたま市浦和区',
  'iwatsuki' => 'さいたま市岩槻区',
  'minami' => 'さいたま市南区',
	'hanyuu' => '羽生市',
	'ageo' => '上尾市',
	'kitamoto' => '北本市',
	'kawaguchi' => '川口市',
	'koshigaya' => '越谷市',
	'kounosu' => '鴻巣市',
	'kawagoe' => '川越市',
	'fujimono' => 'ふじみ野市',
	'fujimi' => '富士見市',
	'sakado' => '坂戸市',
	'turugashima' => '鶴ヶ島市',
	'iruma' => '入間郡',
	'hannnou' => '飯能市',
	'hidaka' => '日高市',
	'kumagaya' => '熊谷市',
	'gyouda' => '行田市',
	'fukaya' => '深谷市',
	'souka' => '草加市',
	'misato' => '三郷市',
	'chichibu' => '秩父市',
	'tokorozawa' => '所沢市',
	'sayama' => '狭山市',
	'kasukabe' => '春日部市',
	'hasuda' => '蓮田市',
	'kuki' => '久喜市',
	'kitakatsushika' => '北葛飾郡',
	'misato' => '三郷市',
	'warabi' => '蕨市',
	'toda' => '戸田市',
);
?>
